# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /run/media/tanner/Whiterun/Soupbox/UE5

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	P3_Flagship-Android-DebugGame  \
	P3_Flagship-Android-Development  \
	P3_Flagship-Android-Shipping  \
	P3_Flagship-Linux-DebugGame  \
	P3_Flagship-Linux-Development  \
	P3_Flagship-Linux-Shipping  \
	P3_Flagship-LinuxArm64-DebugGame  \
	P3_Flagship-LinuxArm64-Development  \
	P3_Flagship-LinuxArm64-Shipping  \
	P3_Flagship \
	P3_FlagshipEditor-Linux-DebugGame  \
	P3_FlagshipEditor-Linux-Development  \
	P3_FlagshipEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend P3_FlagshipEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug P3_FlagshipEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

P3_Flagship-Android-DebugGame:
	 $(BUILD) P3_Flagship Android DebugGame  -Project="/run/media/tanner/Whiterun/Soupbox/UE5_Projects/P3_Flagship/P3_Flagship.uproject" $(ARGS)

P3_Flagship-Android-Development:
	 $(BUILD) P3_Flagship Android Development  -Project="/run/media/tanner/Whiterun/Soupbox/UE5_Projects/P3_Flagship/P3_Flagship.uproject" $(ARGS)

P3_Flagship-Android-Shipping:
	 $(BUILD) P3_Flagship Android Shipping  -Project="/run/media/tanner/Whiterun/Soupbox/UE5_Projects/P3_Flagship/P3_Flagship.uproject" $(ARGS)

P3_Flagship-Linux-DebugGame:
	 $(BUILD) P3_Flagship Linux DebugGame  -Project="/run/media/tanner/Whiterun/Soupbox/UE5_Projects/P3_Flagship/P3_Flagship.uproject" $(ARGS)

P3_Flagship-Linux-Development:
	 $(BUILD) P3_Flagship Linux Development  -Project="/run/media/tanner/Whiterun/Soupbox/UE5_Projects/P3_Flagship/P3_Flagship.uproject" $(ARGS)

P3_Flagship-Linux-Shipping:
	 $(BUILD) P3_Flagship Linux Shipping  -Project="/run/media/tanner/Whiterun/Soupbox/UE5_Projects/P3_Flagship/P3_Flagship.uproject" $(ARGS)

P3_Flagship-LinuxArm64-DebugGame:
	 $(BUILD) P3_Flagship LinuxArm64 DebugGame  -Project="/run/media/tanner/Whiterun/Soupbox/UE5_Projects/P3_Flagship/P3_Flagship.uproject" $(ARGS)

P3_Flagship-LinuxArm64-Development:
	 $(BUILD) P3_Flagship LinuxArm64 Development  -Project="/run/media/tanner/Whiterun/Soupbox/UE5_Projects/P3_Flagship/P3_Flagship.uproject" $(ARGS)

P3_Flagship-LinuxArm64-Shipping:
	 $(BUILD) P3_Flagship LinuxArm64 Shipping  -Project="/run/media/tanner/Whiterun/Soupbox/UE5_Projects/P3_Flagship/P3_Flagship.uproject" $(ARGS)

P3_Flagship: P3_Flagship-Linux-Development

P3_FlagshipEditor-Linux-DebugGame:
	 $(BUILD) P3_FlagshipEditor Linux DebugGame  -Project="/run/media/tanner/Whiterun/Soupbox/UE5_Projects/P3_Flagship/P3_Flagship.uproject" $(ARGS)

P3_FlagshipEditor-Linux-Development:
	 $(BUILD) P3_FlagshipEditor Linux Development  -Project="/run/media/tanner/Whiterun/Soupbox/UE5_Projects/P3_Flagship/P3_Flagship.uproject" $(ARGS)

P3_FlagshipEditor: P3_FlagshipEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/run/media/tanner/Whiterun/Soupbox/UE5_Projects/P3_Flagship/P3_Flagship.uproject" -Game 

.PHONY: $(TARGETS)
